### ISSUE TITLE
Pass advertise data to app

### ISSUE THREAD

**Issue by bradjc** [lab11/summon#17]
Beyond just ID pass in the adv data that triggered the device to show up in the list.

**Comment by tzachari** [comment]
Now supported.

This:

```
new Uint8Array( JSON.parse( gateway.getDeviceAdvertisement() ) )
```

returns what is normally expected when this: 

```
new Uint8Array( device.advertising )
```

is called in the ble scan success callback.

**Comment by brghena** [comment]
Will the advertisement data we are handed just be Eddystone data? If it's the advertisement that made the device appear in the list, it always will be.

Maybe Summon could return the last N advertisements received? Or if it's just the most recent advertisement seen, that at least has some probability of being a data-bearing advertisement.

**Comment by tzachari** [comment]
It is the most recent advertisement seen.

**Comment by brghena** [comment]
It looks like window.gateway.getDeviceAdvertisement() returns a toString
(in java) of a UInt8Array (in javascript). Is there a reason you couldn't
just give us p.advertising directly, no manipulation?

Thanks
Branden Ghena
PhD Student - University of Michigan
Computer Science and Engineering

**Comment by bradjc** [comment]
Also, can we get an array of recent advertisements? With these devices that switch advertisements the key is getting at least one of the data advertisements so we can populate the ui.

**Comment by tzachari** [comment]
The Android Javascript interfacing system only allows return of single primitive values and strings. For instance, if you actually look under the hood of the core Cordova library that implements binding for plugins, it is essentially built on a string-based message-passing system with parsers in Java and Javascript to convert strings into suitable corresponding data types. 

I could, perhaps, provide the values as a Base64 encoded string, but much more would be required on the Javascript side for parsing than just calling JSON.parse, especially if Summon is to provide an array of advertisements.

**Comment by tzachari** [comment]
So, I've changed `gateway.getDeviceAdvertisement()` to return a stringified device object. This, when parsed, is similar to the parameter returned in the scan success callback: 

```
{
    "id": "AB:CD:EF:01:23:45",
    "name": "BleDevice",
    "rssi": -75,
    "advertising": [7,9,85,82,73,...],
    "ads": [ [7,9,85,82,73,...], [...], ...]
}
```

To use it, you can call:

```
device = JSON.parse( gateway.getDeviceAdvertisement() );
```

`device.advertising` provides the ad data as an actual array (instead of an array buffer), but it is safe to call `new Uint8Array( device.advertising )` as would normally be done in a scan callback.

`device.ads` provides an array of unique detected advertisements.

It doesn't look like anyone used the original `gateway.getDeviceAdvertisement()`, so this shouldn't break anyone's UI.
